language: python

dist: bionic
  
  
addons:
  apt:
    config:
      retries: true

cache:
  apt: true
  pip: true

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt-get install -y tesseract-ocr
  - tesseract --version
  - tesseract --list-langs
  - cd tests
  - curl gdrive.sh | bash -s https://drive.google.com/drive/folders/1DoBr_uWeRjeId6V3prx8gNVyVJtjrT4c?usp=sharing
  - mv travis_pytesseract_testimages/* ..
  - cd ..

install:
  - pip install -r requirements.txt

script:
  - nosetests tests/tests.py

notifications:
  email: false