language: python

addons:
  apt:
    config:
      retries: true

cache:
  apt: true
  pip: true

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt install -y tesseract-ocr
  - tesseract --version
  - tesseract --list-langs

install:
  - pip install -r requirements.txt

script:
  - nosetests -v --with-coverage --cover-tests --cover-package=noseselecttests noseselecttests/tests.py

notifications:
  email: false