name: Test on simple dataset

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install nose pytest
        sudo apt-get install -y tesseract-ocr
    - name: Download dataset
      run: |
        cd tests
        curl gdrive.sh | bash -s https://drive.google.com/drive/folders/1DoBr_uWeRjeId6V3prx8gNVyVJtjrT4c?usp=sharing
        mv travis_pytesseract_testimages/* ..
        cd ..
    - name: Test on sample dataset
      run: nosetests
        
